### ISSUE TITLE
Password length longer than 8 characters fails logon

### ISSUE THREAD

**Issue by MnrGreg** [e-mcgee/paradox_platform#1]
Hi @e-mcgee, I've found that a password length longer than 8 characters causes the logon to fail. Haven't debugged much further. Just logging the issue.

Good job by the way bringing this all together!

**Comment by e-mcgee** [comment]
Thanks for the feedback.  I know this has been fixed in one of the projects I used to create this. As soon as Inhave time I will try and provide a fix.

**Comment by aquadat0r** [comment]
+1, would appreciate the fix, great work

**Comment by e-mcgee** [comment]
OK, latest version 0.36 caters for password length.  The problem was that I hardcoded the header to 8 character length password, so it probably only worked for that length anyway.  I now change the header to reflect the actual length of the password.  I tested with my password an it is working so please test with your various passwords an let me know if it is working now.  It only currently caters for up to 16 characters.
