### ISSUE TITLE
Automation with two partitions

### ISSUE THREAD

**Issue by deon-wentzel** [e-mcgee/paradox_platform#14]
Hi

Plugin working well except for the following minor issue.

In Home App, I have created a Scene that turns off all the lights and arms both partitions, the first time I tested the scene it worked and both partitions were armed (away). Sometime when use the scene the one partition arms and the other is in trying... state. If you manually turn it off and select away, while its trying, it arms. If you arm the partitions individually, they both arm..

Any suggestions

**Comment by e-mcgee** [comment]
Hi Deon,

I noticed the same with the PGMs in automations. I suspect what happens is that the commands are both sent to the plugin simultaneously and then only one actually gets actioned by the plugin.  Doing it individually works because they do not happen simultaneously.  This is probably because Node runs each concurrently and neither the plugin nor the alarm can really handle this.
In my previous plugin version that logged in before each command it was much worse as this took very long.  The new plugin stays connected and thus it is less likely to be a problem but as you noticed still happens.  I guess the only way to deal with this may be to create a command queue that remembers all the commands and works them off until they are all actioned.  To do this will mean a bit of designing and work.  Will put it on the backlog to look at when I have time again.

**Comment by e-mcgee** [comment]
Hi Deon,

try the new version.  I modified the alarm controls for bot PGM and arming/disarming to have a delay between commands should they already be busy.  I tested and mine seems to be OK.  Let me know if this resolves your issue.

**Comment by e-mcgee** [comment]
BTW I also shortened the poll loop to 5 seconds so that the status updates happen more often

**Comment by deon-wentzel** [comment]
Thanks will do..

**Comment by e-mcgee** [comment]
Also added MQTT support as suggested so integration with Node-RED should be possible

**Comment by deon-wentzel** [comment]
Hi, So have have been running the updated plug-in for a few days now and I am happy to say it is working well. The plug-in is stable. Thank you for your efforts.

**Comment by iondarie** [comment]
Hello,

There seems to be a problem with arming/disarming 2 partitions. It arms/disarms only the 1-st partition.

Only sometimes it works correctly.

Please help.

Thank you
